Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://www.zenol.fr/site/"
  copyright: © Jérémy Cochoy 2013
  analytics: UA-10762787-1

Development:
  approot: "http://localhost:3000"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.zenol.fr/site/"
  <<: *defaults
